---
- name: add CloudPassage repository
  shell: echo 'deb https://production.packages.cloudpassage.com/debian debian main' | sudo tee /etc/apt/sources.list.d/cloudpassage.list

- name: update apt repositories
  apt:
    update_cache: yes
  become: true
  become_user: root

- name: install curl
  package:
    name: curl
    state: latest

- name: import CloudPassage public key
  get_url:
    url: https://production.packages.cloudpassage.com/cloudpassage.packages.key
    dest: /tmp/cloudpassage_key.txt

- name: add CloudPassage public key
  command: apt-key add /tmp/cloudpassage_key.txt
  become: true
  become_user: root

- name: update apt repositories
  apt:
    update_cache: yes
  become: true
  become_user: root

- name: Check if Package is installed
  command: dpkg-query -l cphalo
  register: is_installed
  failed_when: false

- name: install the daemon
  package:
    name: cphalo
    state: latest
  become: true
  become_user: root
  when: is_installed.rc > 0

- name: Retrieve AWS Instance metadata
  get_url:
    url: http://169.254.169.254/latest/dynamic/instance-identity/document/
    dest: /etc/foo.conf

- name: instance metadata
  command: cat /etc/foo.conf
  register: instance_metadata

- set_fact:
    data: "{{ instance_metadata.stdout }}"

- name: Retrieve AWS InstanceID
  shell: python -c "import json, sys; print {{ data }}['instanceId']"
  register: instance_id

- name: Retrieve AWS accountID
  shell: python -c "import json, sys; print {{ data }}['accountId']"
  register: account_id

- name: configure agent key
  shell: "/opt/cloudpassage/bin/configure --agent-key={{ agent_key }} --grid=https://grid.cloudpassage.com/grid --debug --server-label={{ account_id.stdout }}_{{ instance_id.stdout }}"
  become: true
  become_user: root
  when: is_installed.rc > 0

- name: Check if systemd is installed
  command: dpkg -s systemd
  register: is_systemd_installed
  failed_when: false

- name: Configure systemd
  script: ./systemd_apt_install.sh
  when: is_systemd_installed.rc == 0

- name: Check if upstart is installed
  command: dpkg -s upstart
  register: is_upstart_installed
  failed_when: false

- name: Configure upstart
  script: ./upstart_apt_install.sh
  when: is_systemd_installed.rc == 1 and is_upstart_installed.rc == 0

- name: start the daemon for the first time
  service: name=cphalod state=started
  become: true
  become_user: root
  when: is_installed.rc > 0 and is_systemd_installed.rc > 0 and is_upstart_installed.rc > 0
